phpcs

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -10,7 +10,8 @@ if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
             ~/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs --standard="~/.composer/vendor/drupal/coder/coder_sniffer/Drupal" "$FILE" #1> /dev/null
             if [ $? -ne 0 ]; then
 		~/.composer/vendor/bin/phpcbf  --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal "$FILE"
-                echo -e "\e[1;33m\tWarning, some files do not respecting the Drupal coding standards. Commit was not aborted.\e[0m" >&2
+                echo -e "\e[1;33m\tWarning, some files do not respecting the Drupal coding standards. Commit was aborted.\e[0m" >&2
+		exit 1;
             fi
 
             RESULT=$(grep "dpm(" "$FILE")
@@ -20,5 +21,3 @@ if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
     fi
 fi
 done
-
-exit 1;
